// Ingredient data for the interactive orbs + evidence cards.
// VC content is real; the rest is clearly-marked placeholder copy.
export const INGREDIENTS = [
  {
    id: 'vc',
    name: '抗坏血酸（VC）',
    inci: 'ASCORBIC ACID',
    cas: '50-81-7',
    color: '#ffb347',
    r: 0.15,
    shape: 'sparkle',
    effects: ['抗氧化', '美白提亮', '促胶原合成'],
    dose: '8–20%（文献起效）',
    evidence: { journal: 'Dermatol Surg 2001;27(2):137–42', pmid: '11207686' },
    badge: { level: 'warn', text: '存疑：推断 1.0–13.3%，横跨起效线' },
  },
  {
    id: 've',
    name: '生育酚（VE）',
    inci: 'TOCOPHEROL',
    cas: '59-02-9',
    color: '#ffd166',
    r: 0.115,
    shape: 'ring',
    effects: ['抗氧化', '滋润修护'],
    dose: '0.1–1%（文献起效）',
    evidence: { journal: '文献示例（占位，待接入证据库）', pmid: null },
    badge: { level: 'ok', text: '达标：推断 0.5–1.0%' },
  },
  {
    id: 'fa',
    name: '阿魏酸',
    inci: 'FERULIC ACID',
    cas: '1135-24-6',
    color: '#b18cff',
    r: 0.1,
    shape: 'crystal',
    effects: ['抗氧化增效', '稳定 VC/VE'],
    dose: '≈0.5%（文献起效）',
    evidence: { journal: '文献示例（占位，待接入证据库）', pmid: null },
    badge: { level: 'ok', text: '达标：推断 0.4–0.6%' },
  },
  {
    id: 'na',
    name: '烟酰胺',
    inci: 'NIACINAMIDE',
    cas: '98-92-0',
    color: '#7fd4ff',
    r: 0.095,
    shape: 'glint',
    effects: ['屏障修护', '控油提亮'],
    dose: '2–5%（文献起效）',
    evidence: { journal: '文献示例（占位，待接入证据库）', pmid: null },
    badge: { level: 'info', text: '偏保守：推断 1.2–2.8%' },
  },
  {
    id: 'b5',
    name: '泛醇',
    inci: 'PANTHENOL',
    cas: '81-13-0',
    color: '#a8e6c0',
    r: 0.075,
    shape: 'plain',
    effects: ['保湿', '舒缓'],
    dose: '1–5%（文献起效）',
    evidence: { journal: '文献示例（占位，待接入证据库）', pmid: null },
    badge: { level: 'ok', text: '达标：推断 2–4%' },
  },
]

// drift parameters per orb (kept inside the liquid column)
export const ORBIT = {
  vc: { y: 0.74, ax: 0.30, az: 0.26, ay: 0.14, fx: 0.21, fz: 0.17, fy: 0.26, p: 0.0 },
  ve: { y: 0.46, ax: 0.26, az: 0.24, ay: 0.12, fx: 0.26, fz: 0.22, fy: 0.19, p: 1.3 },
  fa: { y: 0.94, ax: 0.27, az: 0.22, ay: 0.10, fx: 0.19, fz: 0.24, fy: 0.22, p: 2.1 },
  na: { y: 0.62, ax: 0.25, az: 0.27, ay: 0.13, fx: 0.28, fz: 0.25, fy: 0.21, p: 4.2 },
  b5: { y: 0.30, ax: 0.22, az: 0.20, ay: 0.09, fx: 0.25, fz: 0.3, fy: 0.28, p: 5.1 },
}
